### ISSUE TITLE
Add LINK handler

### ISSUE THREAD

**Issue by igorveselinovic** [sysc3010-t3/server#6]

**Comment by igorveselinovic** [comment]
Might not be needed, since we're passing the `car_id` in every movement message.

**Comment by Thao-Tran** [comment]
What are you thinking the `LINK` handler will do? Like the app sends the `LINK` message to the central server with the `car_id` that it wants to link to then does the central server store the pairing in the cache? Would the pairing be `app_ip` -> `car_ip` or `user_id` -> `car_ip`?

**Comment by igorveselinovic** [comment]
The central server would store the pairing of the App's IP address and the car's IP address in cache (so `app_ip` -> `car_ip`). I actually wrote out functions in the `Server` class (`add_route()` and `get_destination()`) for this when I first made it.

**Comment by igorveselinovic** [comment]
But if we're passing the `car_id` in each `MOVE` message, then sending a `LINK` seems redundant.

**Comment by Thao-Tran** [comment]
Ah okay. I mean I like this design more than passing the `car_id` in each `MOVE` message since the `app_ip` is already sent anyway, but whatever's easier I guess.

**Comment by igorveselinovic** [comment]
We can discuss it at the meeting tomorrow.
